import numpy as np
import pygame 
import sys
import time
import random

aaa = {111: [31,23], 123:123}
print random.choice([])

# print(np.array([[1,1],[1,1], [1,1], [1,1]])[0])
# a = [[1,1], [1,2], [1, 3]]
# b = [[1,1]]
# c = np.array([[1,1], [1,2], [1, 3]])
# d = np.array([[2,1]])
# if b in a:
# 	print(1231)
# # a.append([1, 2])
# b.append([1, 2])
# b.append([2, 3])
# a.extend(b)
# # N = np.array()
# # a = np.vstack([N, [1,2]])
# def n():
# 	print("aasda")

# a = n()
# m = [1,1,1,1]
# for i in range(4):
# 	m[i] = i + 1
	
# print(np.sqrt(3))

# for j in range(2):
# 	for i in range(5):
# 		print i
# 		if i == 3:
# 			break
# lll = {}
# for i in range(10):
# 	lll[(i, i)] = i**2

# print lll